name: Linux CI runner for NCM6B

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    name: Test runner
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |         
          sudo apt-get update
          echo This demo file shows a  
          
      - name: Check Device is TTY or Not
        run: |
          if [ -t 1 ]; then
            echo "Output is a TTY"
          else
            echo "Output is not a TTY"
          fi
